import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <header className="border-b bg-slate-900 text-white">
          <nav className="mx-auto flex max-w-5xl flex-wrap items-center gap-x-6 gap-y-2 p-4">
            <a href="/" className="font-bold">Mehak Channa</a>
            <a href="/work" className="text-sm hover:underline">Work</a>
            <a href="/case-study" className="text-sm hover:underline">Case Study</a>
            <a href="/about" className="text-sm hover:underline">About</a>
            <a href="/contact" className="text-sm hover:underline">Contact</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
